paginate = 20
enableEmoji = true
title = "Airscript"
languageCode = "en"
theme = "hugo-coder"
pygmentsStyle = "bw"
pygmentsCodeFences = true
defaultContentLanguage = "en"
baseURL = "https://airscript.it"
pygmentsCodeFencesGuessSyntax = true

[params]
rtl = false
customJS = []
customCSS = []
customSCSS = []
customRemoteJS = []
maxSeeAlsoItems = 5
author = "Airscript"
colorScheme = "auto"
info = ["Software Engineer"]
hideColorSchemeToggle = false
dateFormat = "January 1, 1970"
avatarURL = "images/avatar.png"
favicon_16 = "images/favicon-16x16.png"
favicon_32 = "images/favicon-32x32.png"
touchIcon = "images/apple-touch-icon.png"
description = "Sharing happiness with code."
keywords = "home,airscript,airscripts,software,engineering,developer"

[taxonomies]
tag = "tags"
author = "authors"
category = "categories"

[[params.social]]
weight = 1
name = "Github"
icon = "fa fa-2x fa-github"
url = "https://github.airscript.it"

[[params.social]]
weight = 2
name = "GitLab"
icon = "fa fa-2x fa-gitlab"
url = "https://gitlab.airscript.it"

[[params.social]]
weight = 3
name = "Twitter"
icon = "fa fa-2x fa-twitter"
url = "https://twitter.airscript.it"

[[params.social]]
weight = 4
name = "Mastodon"
icon = "fa fa-2x fa-mastodon"
url = "https://mastodon.airscript.it"

[[params.social]]
weight = 5
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
url = "https://linkedin.airscript.it"

[[params.social]]
weight = 6
name = "More"
icon = "fa fa-2x fa-link"
url = "https://linktree.airscript.it"

[languages.en]
languageName = "en"
contentDir = "content/english"

[[languages.en.menu.main]]
weight = 1
name = "About"
url = "about/"

[[languages.en.menu.main]]
weight = 2
name = "Blog"
url = "https://blog.airscript.it"

[[languages.en.menu.main]]
weight = 3
name = "Projects"
url = "https://github.com/airscripts?tab=repositories"
